---
sudo: required
services:
  - docker
script:
  - 'docker build -t universal-web-fonts .'
after_success:
  - 'docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN'
  - 'docker tag universal-web-fonts $DOCKER_USERNAME/universal-web-fonts:latest'
  - 'docker push $DOCKER_USERNAME/universal-web-fonts:latest'
