---
on:
  push:
    branches: [ "latest" ]
  pull_request:
    branches: [ "latest" ]
  schedule:
    - cron: "40 2 * * 3"

permissions:
  contents: "read"

jobs:
  "build":
    permissions:
      contents: "read"
      security-events: "write"
      actions: "read"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - run: "docker build -t docker.io/my-organization/my-app:${{ github.sha }} ."

      - uses: "aquasecurity/trivy-action@0.7.1"
        with:
          image-ref: "docker.io/my-organization/my-app:${{ github.sha }}"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - uses: "github/codeql-action/upload-sarif@v2"
        with:
          sarif_file: "trivy-results.sarif"
